openapi: 3.0.0
info:
  version: '0.0.1'
  title: Project-Meetime-Backend
  description: Expose all endpoints of project MEETIME 2025
  contact:
    name: Leandro
    email: leandroluz201616@gmail.com
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://localhost:8080/api/v1
    description: Local development server (HTTPS)

paths:
  /oauth2/authorize:
    get:
      tags:
        - OAuth
      summary: Generate the authorization URL for HubSpot OAuth
      description: Generates the URL to start the OAuth flow with HubSpot.
      operationId: generateAuthorizationUrl
      responses:
        '200':
          description: Access token obtained successfully
          content:
            text/plain:
              schema:
                type: string
                example: "https://app.hubspot.com/oauth/authorize?client_id=998bfe92-a1u5-4cc6-ba2c-7ac56a328003&redirect_uri=http://localhost:8080/api/v1/oauth2/callback&scope=crm.objects.contacts.write%20oauth%20crm.objects.contacts.read"
        '302':
          description: Redirect to HubSpot authorization URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /oauth2/callback:
    get:
      tags:
        - OAuth
      summary: Process OAuth callback from HubSpot
      description: Handles the callback from HubSpot and exchanges the authorization code for an access token.
      operationId: handleOAuthCallback
      parameters:
        - name: code
          in: query
          description: Authorization code provided by HubSpot
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Access token obtained successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenHubspotResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authorization Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /contact:
    post:
      tags:
        - Contacts
      summary: Create a new contact in HubSpot
      description: Creates a new contact in HubSpot CRM.
      operationId: createContact
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRequest'
      responses:
        '201':
          description: Contact created successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authorization Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /webhook/contact-creation:
    post:
      tags:
        - Webhooks
      summary: Handle HubSpot contact creation webhook
      description: Processes events of type "contact.creation" sent by HubSpot webhook.
      operationId: handleWebhook
      parameters:
        - name: X-HubSpot-Signature
          in: header
          required: false
          schema:
            type: string
        - name: X-HubSpot-Signature-Version
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookHubspotCreateContactRequest'
      responses:
        '200':
          description: Event processed successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authorization Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /storage/upload:
    post:
      tags:
        - Storage Lambda AWS
      summary: Upload file to S3
      description: Upload a file to AWS S3 bucket directly through Lambda
      operationId: uploadFileToS3
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations
        type: aws_proxy
        httpMethod: POST
        credentials: arn:aws:iam::${account}:role/${role}
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                path:
                  type: string
              required:
                - file
                - path
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: The URL of the uploaded file
                    example: "https://my-bucket.s3.amazonaws.com/folder/file.pdf"
                  key:
                    type: string
                    description: The S3 key of the uploaded file
                    example: "folder/file.pdf"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    AccessTokenHubspotResponse:
      $ref: './components/schemas/access-token-hubspot.yaml'
    ContactRequest:
      $ref: './components/schemas/contact-request.yaml'
    Contact:
      $ref: './components/schemas/contact.yaml'
    WebhookHubspotCreateContactRequest:
      $ref: './components/schemas/webhook-hubspot.yaml#/WebhookHubspotCreateContactRequest'
    WebhookHubspotCreateContact:
      $ref: './components/schemas/webhook-hubspot.yaml#/WebhookHubspotCreateContact'
    Error:
      $ref: './components/schemas/error.yaml'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >
        Insert the JWT token in the format: "Bearer {token}"

security:
  - BearerAuth: []
